// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zgap5-BVpxiRPizRTQoZ5kdTM8pABaE',
    appId: '1:692112608562:web:3d41ce47cfe5b1675f1b2b',
    messagingSenderId: '692112608562',
    projectId: 'movie-server-app',
    authDomain: 'movie-server-app.firebaseapp.com',
    storageBucket: 'movie-server-app.firebasestorage.app',
    measurementId: 'G-6RTLJZY3YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBo7kbTpETTAIUB-hZv5iJlQq2tA8JxOs',
    appId: '1:692112608562:android:77254bcabf6a29f75f1b2b',
    messagingSenderId: '692112608562',
    projectId: 'movie-server-app',
    storageBucket: 'movie-server-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBulqzTLMD6DeUspf0q8mTZe4IauMy_g-0',
    appId: '1:692112608562:ios:7ec5909224aceeab5f1b2b',
    messagingSenderId: '692112608562',
    projectId: 'movie-server-app',
    storageBucket: 'movie-server-app.firebasestorage.app',
    androidClientId: '692112608562-nk1q3nraas6tri8vgrhe6ve1fh4p0kmm.apps.googleusercontent.com',
    iosClientId: '692112608562-pih37v8aqpivvj2fuu5ji09h3aeuuufp.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieServerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBulqzTLMD6DeUspf0q8mTZe4IauMy_g-0',
    appId: '1:692112608562:ios:7ec5909224aceeab5f1b2b',
    messagingSenderId: '692112608562',
    projectId: 'movie-server-app',
    storageBucket: 'movie-server-app.firebasestorage.app',
    androidClientId: '692112608562-nk1q3nraas6tri8vgrhe6ve1fh4p0kmm.apps.googleusercontent.com',
    iosClientId: '692112608562-pih37v8aqpivvj2fuu5ji09h3aeuuufp.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieServerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7zgap5-BVpxiRPizRTQoZ5kdTM8pABaE',
    appId: '1:692112608562:web:602e198589f6f5a05f1b2b',
    messagingSenderId: '692112608562',
    projectId: 'movie-server-app',
    authDomain: 'movie-server-app.firebaseapp.com',
    storageBucket: 'movie-server-app.firebasestorage.app',
    measurementId: 'G-7GGRFTF92D',
  );

}